### ISSUE TITLE
Invalid circular dependencies

### ISSUE THREAD

**Issue by Adamfsk** [inversify/InversifyJS#543]
## Expected Behavior
Class A injects classes B and C. Class B also injects class C. this should work since there is no circular dependency

## Current Behavior
Inversify throws a runtime error that there is a circular dependency "A -> B -> C -> B

## Possible Solution
Modify the code changed in https://github.com/inversify/InversifyJS/pull/353 to correctly calculate circular dependencies instead of reporting every matching import in the same chain as circular. A -> B -> A is a circular dependency, but the case mentioned is not.

## Steps to Reproduce (for bugs)
1. Class A injects two classes B and C
2. Class B injects C
3. View runtime error

## Context
I'm using an event bus object throughout my application. this previously worked without problems but is now causing a runtime error.

## Your Environment
Typescript 2.3 compiler, webpack 2, Chrome latest version, Windows 10 desktop.

**Comment by remojansen** [comment]
@Adamfsk thanks for reporting this issue. I will try to fix it ASAP (Probably during the weekend). If this is blocking you. I would recommend using [lazyInject](https://github.com/inversify/inversify-inject-decorators) as a temporal work around.

**Comment by Adamfsk** [comment]
I might be wrong about this issue.. I've found out that I DO actually have a circular dependency, but the error output is completely incorrect. It's in an entirely different location including none of the classes mentioned in the error message. I'll see if I can create an example project but it might be somewhat difficult! There's definitely something not working correctly here though.

**Comment by remojansen** [comment]
@Adamfsk that sounds like it could be possible. We detect circular dependencies because the resolver enters into an infinite loop and there is a stack overflow. We catch that exception and try to find out the cause by exploring a list of the most recent resolved entities. However, the stack overflow takes place in different moments in different JS engines. Will try to see if I can reproduce it but if you can provide a test case that will be much appreciated.

**Comment by remojansen** [comment]
The following works for me:

```ts
@injectable()
class C {
    public name = "C";
}

@injectable()
class B {
    public name = "B";
    @inject("C") public c: C;
}

@injectable()
class A {
    public name = "A";
    @inject("B") public b: B;
    @inject("C") public c: C;
}

const container =  new Container();
container.bind<A>("A").to(A);
container.bind<B>("B").to(B);
container.bind<C>("C").to(C);

let a = container.get<A>("A");
expect(a.name).eql("A");
expect(a.b.name).eql("B");
expect(a.c.name).eql("C");
expect(a.b.c.name).eql("C");
```

The dependency graph here looks like:

```
└──A
   ├── B
   |   └── C
   └── C
```

What does your dependency graph look like?

**Comment by remojansen** [comment]
@Adamfsk any luck with this?

**Comment by showplans** [comment]
I'm having exactly this issue. It's correctly reporting that a circular dependency exists, but the list of classes given is complete nonsense (it includes classes that don't have any dependencies, for example). Unfortunately this is in a complex project that I'm not at liberty to share, but if I have any spare time I'll try and create a test case.

**Comment by remojansen** [comment]
Hi @showplans, can you share some information about your environment? Node version, ts version etc? A test case would be much appreciated 👍

**Comment by cdibbs** [comment]
I am having this issue, also. The list of classes, as @showplans mentioned, doesn't make any sense, with some having no dependencies at all. If I get some time, I'll try to dig deeper and see what's going on.

**Comment by cdibbs** [comment]
It would be better to show no list of classes in the circular dependency error than to have the list be inaccurate and send developers on a goose chase. Once I got back to it, this evening, I discovered _I did_ have a circular dependency, but it was not on a class listed by the error message. Resolving that circular dep indeed cleared the error.

In case it helps the maintainers: the error was that I accidentally typed `@inject(Token_ThisClassItself)` rather than the actual dep.

My advice to anyone encountering the error: ignore the error message content, and just `git diff` to see what you've changed recently. :-)

**Comment by remojansen** [comment]
👍 Thanks for the insights, It is clear that we have a bug that no one has been able to reproduce so far. The list of classes works in some cases because circular dependencies have been detected correctly in our unit tests. I will try to investigate once more but again without a tests case is very hard to do anything about it 😢

**Comment by cdibbs** [comment]
Hey, I think I found a way to demo the bug.

```typescript
import { injectable, inject, multiInject, Container } from 'inversify';
import 'reflect-metadata';

let tokens = {
    Kernel: Symbol("Kernel"),
    First: Symbol("First"),
    Circular: Symbol("Circular"),
    Irrelevant: Symbol("Irrelevant")
}

@injectable()
class Real {

}

@injectable()
class Circular {
    constructor(
        @inject(tokens.Circular /* my oops */) real: Real
    ) {}
}

@injectable()
class First {
    constructor(
        @inject(tokens.Circular /* valid */) circ: Circular
    ) {}
}

@injectable()
class Irrelevant {

}

@injectable()
class Kernel {

    constructor(
        @inject(tokens.Irrelevant) private another: Irrelevant,
        @multiInject(tokens.First) private first: First) {

    }
}

var container = new Container();
container.bind<Kernel>(tokens.Kernel).to(Kernel);
container.bind<First>(tokens.First).to(First);
container.bind<Circular>(tokens.Circular).to(Circular);
container.bind<Irrelevant>(tokens.Irrelevant).to(Irrelevant);

container.get(tokens.Kernel);
```

This outputs the following error for me:
`Error: Circular dependency found: Symbol(Kernel) -> Symbol(Irrelevant) -> Symbol(First) -> Symbol(First)`

If I change from `@multiInject` to `@inject`, the error message still includes `Irrelevant`, but at least shows the correct circular ref class, at the end:

`Error: Circular dependency found: Symbol(Kernel) -> Symbol(Irrelevant) -> Symbol(First) -> Symbol(Circular) -> Symbol(Circular)`

Hope this helps! Thanks for your work on this library.

**Comment by marvinroger** [comment]
There's definitely something wrong here. I have a sample project that shows the circular dependency message. The git diff (before and after error message) is here: https://github.com/marvinroger/iot/compare/bc2d7b84b916d33366fbb9addd0b935c1a1b687c...7ee14cca69bef026f88ada38e826b824961b8be9

I added two classes: `WsBroadcaster` and `RequestResponder`, and they don't have any circular dependency. Also, weird thing: if you remove the `WsServer` injection in `WsBroadcaster`, the issue disappears - even though `WsServer`and `WsBroadcaster` don't require each other -.

**Comment by aequasi** [comment]
Also having the same issue here:

```
└──API
   ├── ServiceFactory
   |   └── EventEmitter
   └── EventEmitter
```

Throwing a circular reference exception

**Comment by nros** [comment]
Hm I do not understand the last example. Does not class `Circular` uses a circular dependency on itself and thus must fail? To me it seems as if `inversify` IS working properly -  where I am wrong?

Class `Circular` needs an instance injected that is based on `tokens.Circular` but `Circular` is the one to be bound to that token: `container.bind<Circular>(tokens.Circular).to(Circular);`. So to resolve that token an instance of `Circular` is needed which can not be created because initially the token was not resolved - [chicken - egg problem](https://en.wikipedia.org/wiki/Chicken_or_the_egg). To me this seems a classical circular dependency, isn't it?

Am I misunderstanding the example?

**Comment by Adamfsk** [comment]
Hi Nick,

The issue here is that the error message points to the wrong classes when reporting the circular dependencies. In my case it was completely wrong and would have been a wild goose chase if I didn't have in depth knowledge of the system that we'd coded. It often includes irrelevant classes in the list, and sometimes doesn't even include the ones that are causing the circular dependency!

**Comment by remojansen** [comment]
This is now fixed 🎉 https://github.com/inversify/InversifyJS/pull/716 it will be available in the next release.

**Comment by n0minal** [comment]
I'm still having the same issue in 2020


Circular dependency found: Symbol(ExchangeController) --> Symbol(ExchangeService) --> Symbol(CurrencyService) --> Symbol(ExchangeService)
